## 01 - FILTER_CAGED_SP_SALARY_PREDICTION

DRIVE VINCULATION

In [4]:
# Loading in Colab Environment 
from google.colab import drive 
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

LIBRARIES USED

In [5]:
import pandas as pd 
pd.set_option('display.max_columns', None)

import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings( 'ignore' )
plt.style.use("fivethirtyeight")

### INICIAL FILTER - PROFESSIONS

IMPORTING DATAS

In [7]:
df = pd.read_csv("/content/drive/MyDrive/Tera_projetoDemoday/Entregas/CAGEDMOV202207.txt",  
            sep = ';', # the separator of columns (generally is ',' or ';')
            header = 0, # header = line with the labels of columns
            decimal = '.', # python works with '.' as decimal separator 
            encoding='UTF-8', # or 'Latin-1' for some special characters: ~ ´ ` ç
            )
ocup = pd.read_excel('/content/drive/MyDrive/Tera_projetoDemoday/Entregas/layout_caged.xlsx', sheet_name='cbo2002ocupação')

In [8]:
df.head(3)

,competênciamov,região,uf,município,seção,subclasse,saldomovimentação,cbo2002ocupação,categoria,graudeinstrução,idade,horascontratuais,raçacor,sexo,tipoempregador,tipoestabelecimento,tipomovimentação,tipodedeficiência,indtrabintermitente,indtrabparcial,salário,tamestabjan,indicadoraprendiz,origemdainformação,competênciadec,indicadordeforadoprazo,unidadesaláriocódigo,valorsaláriofixo
0,202207,2,26,261160,N,8121400,-1,351305,101,7,47.0,"44,00",3,1,0,1,31,0,0,0,"2403,79",7,0,1,202207,0,5,"2403,79"
1,202207,4,41,410400,P,8591100,-1,422105,101,7,25.0,"57,00",6,3,0,1,40,0,0,0,"1524,60",1,0,1,202207,0,5,"1524,60"
2,202207,2,25,250400,G,4691500,1,784105,101,7,24.0,"30,00",1,1,0,1,97,1,0,1,"826,50",7,0,1,202207,0,5,"826,50"

In [9]:
ocup.head(3)

    Código              descricao_ocupacao
0  10105.0  Oficial General da Aeronautica
1  10110.0     Oficial General do Exercito
2  10115.0      Oficial General da Marinha

DATA INFORMATIONS

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3554172 entries, 0 to 3554171
Data columns (total 28 columns):
 #   Column                  Dtype
---  ------                  -----
 0   competênciamov          int64
 1   região                  int64
 2   uf                      int64
 3   município               int64
 4   seção                   object
 5   subclasse               int64
 6   saldomovimentação       int64
 7   cbo2002ocupação         int64
 8   categoria               int64
 9   graudeinstrução         int64
 10  idade                   float64
 11  horascontratuais        object
 12  raçacor                 int64
 13  sexo                    int64
 14  tipoempregador          int64
 15  tipoestabelecimento     int64
 16  tipomovimentação        int64
 17  tipodedeficiência       int64
 18  indtrabintermitente     int64
 19  indtrabparcial          int64
 20  salário                 object
 21  tamestabjan             int64
 22  indicadoraprendiz       int64
 23  origemdainformação      int64
 24  competênciadec          int64
 25  indicadordeforadoprazo  int64
 26  unidadesaláriocódigo    int64
 27  valorsaláriofixo        object
dtypes: float64(1), int64(23), object(4)
memory usage: 759.3+ MB

In [11]:
ocup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Código              2718 non-null   float64
 1   descricao_ocupacao  2718 non-null   object
dtypes: float64(1), object(1)
memory usage: 42.6+ KB

MERGE

In [14]:
data = df.merge(ocup, # which dataframe to merge
                             how = 'inner', # how to merge the dfs: 'inner', 'outer', 'left', 'right'                    
                             left_on = 'cbo2002ocupação', # what is the label of key in the left dataframe
                             right_on = 'Código' # what is the label of key in the right dataframe
                             ).drop(columns = ['Código'])

In [16]:
data.columns

Index(['competênciamov', 'região', 'uf', 'município', 'seção', 'subclasse',
       'saldomovimentação', 'cbo2002ocupação', 'categoria', 'graudeinstrução',
       'idade', 'horascontratuais', 'raçacor', 'sexo', 'tipoempregador',
       'tipoestabelecimento', 'tipomovimentação', 'tipodedeficiência',
       'indtrabintermitente', 'indtrabparcial', 'salário', 'tamestabjan',
       'indicadoraprendiz', 'origemdainformação', 'competênciadec',
       'indicadordeforadoprazo', 'unidadesaláriocódigo', 'valorsaláriofixo',
       'descricao_ocupacao'],
      dtype='object')

In [15]:
data.head(3)

,competênciamov,região,uf,município,seção,subclasse,saldomovimentação,cbo2002ocupação,categoria,graudeinstrução,idade,horascontratuais,raçacor,sexo,tipoempregador,tipoestabelecimento,tipomovimentação,tipodedeficiência,indtrabintermitente,indtrabparcial,salário,tamestabjan,indicadoraprendiz,origemdainformação,competênciadec,indicadordeforadoprazo,unidadesaláriocódigo,valorsaláriofixo,descricao_ocupacao
0,202207,2,26,261160,N,8121400,-1,351305,101,7,47.0,"44,00",3,1,0,1,31,0,0,0,"2403,79",7,0,1,202207,0,5,"2403,79",Tecnico em Administracao
1,202207,4,43,431440,P,8599604,-1,351305,101,7,26.0,"44,00",1,1,0,1,31,0,0,0,"1728,39",4,0,1,202207,0,5,"1728,39",Tecnico em Administracao
2,202207,3,35,355030,F,4120400,1,351305,101,6,33.0,"20,00",1,3,0,1,97,1,0,0,"1000,00",9,0,1,202207,0,5,"1000,00",Tecnico em Administracao

FILTER

In [18]:
# Filtering (uf = SP | city = São Paulo | CBO = 212 [Aréas relacionadas a tecnologia])
df1 = data[(data.uf == 35) & (data.município == 355030) & (data.cbo2002ocupação.isin([212205, 212210, 212215, 212305, 212310, 212315, 212320, 212405, 212410, 212415, 212420, 212425, 212430]))]
df1.head(3)

,competênciamov,região,uf,município,seção,subclasse,saldomovimentação,cbo2002ocupação,categoria,graudeinstrução,idade,horascontratuais,raçacor,sexo,tipoempregador,tipoestabelecimento,tipomovimentação,tipodedeficiência,indtrabintermitente,indtrabparcial,salário,tamestabjan,indicadoraprendiz,origemdainformação,competênciadec,indicadordeforadoprazo,unidadesaláriocódigo,valorsaláriofixo,descricao_ocupacao
2351401,202207,3,35,355030,J,6201501,1,212415,101,9,35.0,"40,00",1,1,0,1,97,0,0,0,"5000,00",5,0,1,202207,0,5,"5000,00",Analista de Sistemas de Automacao
2351413,202207,3,35,355030,J,6204000,1,212415,101,9,34.0,"40,00",4,1,0,1,97,0,0,0,"8600,00",10,0,1,202207,0,5,"8600,00",Analista de Sistemas de Automacao
2351418,202207,3,35,355030,J,6201501,-1,212415,101,8,40.0,"40,00",3,1,0,1,40,0,0,0,"5153,59",7,0,1,202207,0,5,"5153,59",Analista de Sistemas de Automacao

DROP

In [31]:
df1 = df1.drop(columns=['competênciamov', 'região', 'uf','município', 'competênciadec'])

CHANGING LABELS

In [32]:
df1.columns

Index(['seção', 'subclasse', 'saldomovimentação', 'cbo2002ocupação',
       'categoria', 'graudeinstrução', 'idade', 'horascontratuais', 'raçacor',
       'sexo', 'tipoempregador', 'tipoestabelecimento', 'tipomovimentação',
       'tipodedeficiência', 'indtrabintermitente', 'indtrabparcial', 'salário',
       'tamestabjan', 'indicadoraprendiz', 'origemdainformação',
       'indicadordeforadoprazo', 'unidadesaláriocódigo', 'valorsaláriofixo',
       'descricao_ocupacao'],
      dtype='object')

In [44]:
df1.columns = ['secao', 'subclasse', 'saldomov', 'cbo2002',
       'categoria', 'grau', 'idade', 'horascontratuais', 'racacor',
       'sexo', 'tipoempregador', 'tipoestabelecimento', 'tipomovimentacao',
       'tipodedeficiencia', 'indtrabintermitente', 'indtrabparcial', 'salario',
       'tamestabjan', 'indicadoraprendiz', 'origemdainformação',
       'indicadordeforadoprazo', 'unidadesalariocodigo', 'valorsalariofixo',
       'nome_ocu']

In [48]:
df1.head()

,secao,subclasse,saldomov,cbo2002,categoria,grau,idade,horascontratuais,racacor,sexo,tipoempregador,tipoestabelecimento,tipomovimentacao,tipodedeficiencia,indtrabintermitente,indtrabparcial,salario,tamestabjan,indicadoraprendiz,origemdainformação,indicadordeforadoprazo,unidadesalariocodigo,valorsalariofixo,nome_ocu
2351401,J,6201501,1,212415,101,9,35.0,"40,00",1,1,0,1,97,0,0,0,"5000,00",5,0,1,0,5,"5000,00",Analista de Sistemas de Automacao
2351413,J,6204000,1,212415,101,9,34.0,"40,00",4,1,0,1,97,0,0,0,"8600,00",10,0,1,0,5,"8600,00",Analista de Sistemas de Automacao
2351418,J,6201501,-1,212415,101,8,40.0,"40,00",3,1,0,1,40,0,0,0,"5153,59",7,0,1,0,5,"5153,59",Analista de Sistemas de Automacao
2351427,G,4642701,1,212415,101,7,23.0,"44,00",6,3,0,1,97,0,0,0,"3000,00",3,0,1,0,5,"3000,00",Analista de Sistemas de Automacao
2351448,J,6201501,1,212415,101,9,31.0,"40,00",1,1,0,1,97,0,0,0,"7500,00",9,0,1,0,5,"7500,00",Analista de Sistemas de Automacao

In [49]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8778 entries, 2351401 to 3529277
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   secao                   8778 non-null   object
 1   subclasse               8778 non-null   int64
 2   saldomov                8778 non-null   int64
 3   cbo2002                 8778 non-null   int64
 4   categoria               8778 non-null   int64
 5   grau                    8778 non-null   int64
 6   idade                   8778 non-null   float64
 7   horascontratuais        8777 non-null   object
 8   racacor                 8778 non-null   int64
 9   sexo                    8778 non-null   int64
 10  tipoempregador          8778 non-null   int64
 11  tipoestabelecimento     8778 non-null   int64
 12  tipomovimentacao        8778 non-null   int64
 13  tipodedeficiencia       8778 non-null   int64
 14  indtrabintermitente     8778 non-null   int64
 15  indtrabparcial          8778 non-null   int64
 16  salario                 8778 non-null   object
 17  tamestabjan             8778 non-null   int64
 18  indicadoraprendiz       8778 non-null   int64
 19  origemdainformação      8778 non-null   int64
 20  indicadordeforadoprazo  8778 non-null   int64
 21  unidadesalariocodigo    8778 non-null   int64
 22  valorsalariofixo        8778 non-null   object
 23  nome_ocu                8778 non-null   object
dtypes: float64(1), int64(18), object(5)
memory usage: 1.7+ MB

In [47]:
# FUNCTION TO CHANGE STRINGS UTF-8  df1.rename(columns=lambda x: x.replace('ç': 'c','ã':'a' ), inplace=True)

EXPORT CSV

In [46]:
df1.to_csv('/content/drive/MyDrive/Tera_projetoDemoday/Entregas/1_filter.csv')